# Metody tworzenia tensorów.

In [1]:
# 1. wywołanie konstruktora wymaganego typu.

import torch
import numpy as np
a = torch.FloatTensor(3, 2)
a

tensor([[1.4923e-28, 4.4940e-41],
        [1.4923e-28, 4.4940e-41],
        [0.0000e+00, 0.0000e+00]])

In [2]:
a.zero_() # zerowanie pamięci tensora
# jest to operacja lokalna - przetwarza zawartość tensora i zwraca zmodyfikowany obiekt
# drugim możliwym typem operacji jest operacja funkcyjna - tworzy kopię tensora zawierającą modyfikację, nie zmieniając oryginalnego
# operacje lokalne są bardziej wydajne: szybsze i zużywają mniej pamięci

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [3]:
# 2. konwersja tablicy NumPy lub listy Python - typ tensora określony zostaje na podstawie typu tablicy

torch.FloatTensor([[1, 2, 3], [3, 2, 1]]) # lista list

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [4]:
n = np.zeros(shape=(3, 2)) # tablica NumPy 3 x 2 wypełniona zerami
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
b = torch.tensor(n) # rzutowanie tablicy NumPy na tensor - za pomocą metody "torch.tensor"
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [6]:
# zmiana domyślnego typu danych float
# domyślnie użyty jest float 64-bitowy
# w uczeniu głębokim nie potrzebujemy podwójnej precyzji, więc powszechnie używa się typu 32-bitowego
# możemy przekazać typ danych do utworzonej tablicy NumPy

n = np.zeros(shape=(3, 2), dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [7]:
# alternatywny sposób - przekazanie typu danych do tensora

n = np.zeros(shape=(3, 2))
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
# 3. jawne utworzenie tensora przez bibliotekę PyTorch i wypełnienie go określonymi danymi

torch.zeros(size=(3, 2)) # tensor wypełniony zerami o wymiarach 3 x 2

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
torch.ones(size=(3, 2)) # tensor wypełniony jedynkami o wymiarach 3 x 2

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
torch.eye(n=3) # macierz jednostkowa o wymiarach 3 x 3

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
torch.tensor(data=(1, 2, 3)) # tensor z krotki

tensor([1, 2, 3])

# Tensory skalarne.

In [12]:
# tensory o zerowym wymiarze
# mogą być wynikiem takich operacji, jak suma wszystkich wartości w wektorze

a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [13]:
s = a.sum() # suma wszystkich wartości tensora - wynikiem tensor skalarny
s

tensor(6)

In [14]:
s.item() # dostęp do rzeczywistej wartości tensora

6

In [15]:
torch.tensor(1) # jawne utworzenie tensora skalarnego

tensor(1)

# Tensory GPU.

In [16]:
a = torch.FloatTensor([2, 3]) # utworzenie tensora w procesorze
a

tensor([2., 3.])

In [17]:
ca = a.to('cuda') # przeniesienie tensora do karty graficznej
ca

tensor([2., 3.], device='cuda:0')

# Tensory a gradienty.

In [18]:
# tensory posiadają atrybuty związane z gradientami:

# "grad":
# tensor o takim samym kształcie, jak oryginalny, zawierający wyznaczone gradienty

# "is_leaf":
# o wartości True w razie skonstruowania przez użytkownika
# o wartości False w razie wygenerowania w wyniku transformacji funkcji

# "requires_grad":
# wartość równa True, jeżeli tensor wymaga obliczenia gradientów
# dziedziczony z węzłów liści, inicjalizowanych wartościami podczas konstruowania tensora
# domyślnie wartość False - trzeba wyraźnie określić, czy dla tensora mają być wyznaczone gradienty

v1 = torch.tensor([1.0, 1.0], requires_grad=True) # tensor wymaga wyznaczenia gradientu
v2 = torch.tensor([2.0, 2.0]) # domyślnie "requires_grad=False"

v_sum = v1 + v2 # dodajemy do siebie tensory - powstaje wektor [3.0, 3.0]
v_res = (v_sum*2).sum() # podwajamy każdy element, po czym sumujemy elementy

v_res

tensor(12., grad_fn=<SumBackward0>)

In [19]:
v1.is_leaf, v2.is_leaf # sprawdzamy, czy tensory są węzłami liści

(True, True)

In [20]:
v_sum.is_leaf, v_res.is_leaf

(False, False)

In [21]:
v1.requires_grad, v2.requires_grad, v_sum.requires_grad, v_res.requires_grad # sprawdzamy, czy tensory wymagają obliczenia gradientu

(True, False, True, True)

In [22]:
v_res.backward() # obliczenie pochodnej zmiennej v_res w odniesieniu do dowolnej zmiennej zawartej w grafie
v1.grad # wyznaczone gradienty dla tensora v1

tensor([2., 2.])

In [23]:
v2.grad # dla tensora v2 brak gradientu, ze względu na domyślną wartość parametru